service: ecs-events

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:publish"
      Resource:
        - Ref: ECSStateChangeTopic

functions:
  state-change:
    handler: state-change/index.handler
    environment:
      TOPIC_ARN:
        Ref: ECSStateChangeTopic
      MODE: errors # possible other values are 'all' and 'success'
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.ecs
            detail-type:
              - ECS Task State Change
            detail:
              # clusterArn:
              #   - arn:aws:ecs:eu-west-1:000000000000:cluster/example-cluster-arn
              lastStatus:
                - STOPPED
              stoppedReason:
                - Essential container in task exited
                # - Task stopped by user

resources:
  Outputs:
    ECSStateChangeTopic:
      Description: ECS State Change Topic ARN
      Value:
        Ref: ECSStateChangeTopic
  Resources:
    ECSStateChangeTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ECS State Change
        TopicName: ECSStateChangeTopic
    # # Subscribe to SNS topic -> remove #s to enable resource
    # ECSStateChangeSubscription:
    #   Type: AWS::SNS::Subscription
    #   Properties:
    #     Endpoint: my.email@example.com
    #     Protocol: email
    #     TopicArn:
    #       Ref: ECSStateChangeTopic
